package emit

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/sova-lang/sova-fonts/internal/config"
	"github.com/sova-lang/sova-fonts/internal/google"
)

// Emit returns the rendered Sova file contents for the supplied font results. Caller writes to disk (and stages the WOFF2 bytes); this package is pure formatting so it stays trivially unit-testable.
//
// Path semantics for `@asset(...)`: paths are relative to the generated sova file's directory because that's how `pass_resolve_assets` resolves them in the Sova compiler (against the declaring file's directory, not the project root). The caller knows where both ends sit and computes the relative path; we just embed the strings.
func Emit(m config.Manifest, results []*google.Result, assetRelPaths map[string]string) string {
	var b strings.Builder
	b.WriteString("// CODE GENERATED BY sova-fonts. DO NOT EDIT.\n")
	b.WriteString("// Regenerate with `sova-fonts generate`.\n\n")
	fmt.Fprintf(&b, "package %s on %s\n\n", m.Output.SovaPackage, m.Output.SovaSide)

	for _, r := range results {
		emitOneFamily(&b, r, assetRelPaths)
	}
	return b.String()
}

func emitOneFamily(b *strings.Builder, r *google.Result, assetRelPaths map[string]string) {
	if r == nil || len(r.Faces) == 0 {
		return
	}
	familyConst := familyConstName(r.Request.Family)
	fmt.Fprintf(b, "// %s — %d face(s) staged from %s.\n", r.Request.Family, len(r.Faces), sourceLabel(r.Request.Source))

	assetNames := make([]string, len(r.Faces))
	for i, face := range r.Faces {
		assetNames[i] = assetVarName(familyConst, i)
		rel, ok := assetRelPaths[face.LocalName]
		if !ok {
			rel = "./" + face.LocalName
		}
		fmt.Fprintf(b, "@asset(%q)\n", rel)
		fmt.Fprintf(b, "const %s: string = \"\"\n\n", assetNames[i])
	}

	fmt.Fprintf(b, "const %sCSS: string =\n", familyConst)
	for i, face := range r.Faces {
		rule := renderFontFace(r.Request, face, assetNames[i])
		sep := " +"
		if i == len(r.Faces)-1 {
			sep = ""
		}
		fmt.Fprintf(b, "    %s%s\n", rule, sep)
	}
	b.WriteString("\n")
}

// renderFontFace produces one CSS `@font-face { ... }` rule as a Sova string-concat expression. The asset-URL is interpolated as `+ <assetVar> +` so it picks up the runtime URL the compiler resolved (which carries the content hash → automatic cache busting). Unicode-range is preserved verbatim so per-subset splitting still works in the browser.
func renderFontFace(req google.FontRequest, face google.FetchedFace, assetVar string) string {
	var b strings.Builder
	b.WriteString(`"@font-face { `)
	fmt.Fprintf(&b, "font-family: '%s'; ", escapeSingle(face.Family))
	style := "normal"
	if face.Italic {
		style = "italic"
	}
	fmt.Fprintf(&b, "font-style: %s; ", style)
	weight := face.Weight
	if weight == 0 {
		weight = 400
	}
	if face.IsVariable() {
		fmt.Fprintf(&b, "font-weight: %d %d; ", weight, face.WeightMax)
	} else {
		fmt.Fprintf(&b, "font-weight: %d; ", weight)
	}
	if req.Display != "" {
		fmt.Fprintf(&b, "font-display: %s; ", req.Display)
	}
	b.WriteString(`src: url('" + `)
	b.WriteString(assetVar)
	b.WriteString(` + "') format('woff2');`)
	if face.UnicodeRange != "" {
		fmt.Fprintf(&b, ` unicode-range: %s;`, face.UnicodeRange)
	}
	b.WriteString(` }"`)
	return b.String()
}

// familyConstName turns a Family display name into a CamelCase identifier safe to use as a Sova const name. "Inter" → "Inter"; "JetBrains Mono" → "JetBrainsMono"; "Source Sans 3" → "SourceSans3".
func familyConstName(family string) string {
	var b strings.Builder
	upNext := true
	for _, r := range family {
		switch {
		case unicode.IsLetter(r):
			if upNext {
				b.WriteRune(unicode.ToUpper(r))
			} else {
				b.WriteRune(r)
			}
			upNext = false
		case unicode.IsDigit(r):
			b.WriteRune(r)
			upNext = false
		default:
			upNext = true
		}
	}
	if b.Len() == 0 {
		return "Font"
	}
	return b.String()
}

// assetVarName returns the unexported const name for face #i of a given family. Underscored prefix mirrors the "private to this file" convention used elsewhere in the Sova standard library; numeric suffix keeps names unique across many faces of one family.
func assetVarName(familyConst string, idx int) string {
	return fmt.Sprintf("__%sFace%d", lowerFirst(familyConst), idx)
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	rs := []rune(s)
	rs[0] = unicode.ToLower(rs[0])
	return string(rs)
}

// escapeSingle escapes single-quote characters in the family name (some Google fonts include apostrophes — rare but real). The font-family value uses single-quoted CSS so any embedded single-quote would terminate the string early.
func escapeSingle(s string) string {
	return strings.ReplaceAll(s, "'", `\'`)
}

// sourceLabel renders the human-readable name for a source slug, used only in the trailing comment of each family block in the generated file. Falls back to the raw slug for unknown sources so future drivers (adobe, etc.) still produce a sensible comment without needing this file edited.
func sourceLabel(source string) string {
	switch source {
	case "google":
		return "Google Fonts"
	case "bunny":
		return "Bunny Fonts"
	case "local":
		return "local files"
	case "":
		return "unknown source"
	}
	return source
}

// RelativeAssetPath computes the `@asset` argument the gen file should use to reference one staged WOFF2. Walks from the gen-file's directory to the asset-file's directory; works correctly when those paths cross siblings (e.g. `src/gen/fonts.sova` referencing `assets/fonts/inter-400.woff2` produces `../../assets/fonts/inter-400.woff2`).
func RelativeAssetPath(sovaFileAbs, assetAbs string) (string, error) {
	dir := filepath.Dir(sovaFileAbs)
	rel, err := filepath.Rel(dir, assetAbs)
	if err != nil {
		return "", err
	}
	return filepath.ToSlash(rel), nil
}

// SortedFaces returns the result's faces in the standard display order: weight asc, then upright before italic. Useful for emitter callers that want stable ordering across runs.
func SortedFaces(r *google.Result) []google.FetchedFace {
	cp := append([]google.FetchedFace{}, r.Faces...)
	sort.SliceStable(cp, func(i, j int) bool {
		if cp[i].Weight != cp[j].Weight {
			return cp[i].Weight < cp[j].Weight
		}
		return !cp[i].Italic && cp[j].Italic
	})
	return cp
}
